apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  creationTimestamp: null
  name: myproject-clone-build-push
spec:
  params:
    - description: registry-domain/namespace where the output image should be pushed.
      name: image-registry-url
      type: string
  tasks:
    - name: clone-1
      params:
        - name: url
          value: '<TODO: insert git repo url>'
        - name: revision
          value: main
        - name: deleteExisting
          value: "true"
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: myproject-shared-data
    - name: build-push-1
      params:
        - name: IMAGE
          value: $(params.image-registry-url)/aspnetapp
        - name: DOCKERFILE
          value: '<TODO: insert path to the Dockerfile>'
        - name: CONTEXT
          value: '<TODO: insert path to the directory containing Dockerfile>'
      runAfter:
        - clone-1
      taskRef:
        name: kaniko
      workspaces:
        - name: source
          workspace: myproject-shared-data
  workspaces:
    - description: This workspace will receive the cloned git repo and be passed to the kaniko task for building the image.
      name: myproject-shared-data
